resultado = input("Ingresa tu edad:")
print(type(resultado))
numero = int(resultado)
print(type(numero))
str(22)
float("22.13")
bool("un string")
bool(0)
bol = bool(resultado)
print(bol)
float = float(resultado)
print(float)
